spring.application.name=sleep-backend

# ??????????? ? ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/sleep_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate ?????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT ?????????
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# ?????? ??????????? ??????
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ???????????
logging.level.temp.app.sleepbackend=DEBUG
logging.level.org.springframework.security=DEBUG

# AI ?????? ?????????
app.upload-dir=C:/uploads/
app.python-script=C:/Users/77077/PycharmProjects/sleep_analysis/main.py
